# Example Config to create a domain/dominion
uuid = "GUID-2" # unique UUID

port = 9200 # doesn't matter for the most part, the domain will find other domains on any functioning port

traits = [
	"npBar",
	"compute",
]

# All timings are in Nanoseconds
dialtimeout = 100000000
isolationCheck = 5000000000
serviceCheck = 2000000000
